In [1]:
import numpy as np 
data=[1,2,3,4,5,6]
a1=np.array(data)
a1

array([1, 2, 3, 4, 5, 6])

In [3]:
data=[[1,2,3,4],[5,6,7,8]]
a2=np.array(data)
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
a1.ndim

1

In [5]:
a2.ndim

2

In [6]:
a3=np.array([12,23,34,45])
a3

array([12, 23, 34, 45])

In [11]:
a4=np.array([1,2,3,4],ndmin=5)
a4

array([[[[[1, 2, 3, 4]]]]])

In [13]:
a4.ndim

5

In [14]:
a1.shape

(6,)

In [15]:
a2.shape

(2, 4)

In [16]:
a2.shape[0]

2

In [17]:
a2.shape[1]

4

In [18]:
a2.size

8

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [23]:
a=np.array([10,20,30,40])
new_a=a.reshape(2,2)
new_a

array([[10, 20],
       [30, 40]])

In [25]:
np.reshape(a,(2,2))

array([[10, 20],
       [30, 40]])

In [26]:
a5=np.arange(0,10)
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.reshape(a5,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
np.reshape(a5,(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
a5[2]

2

In [30]:
a5[5]

5

In [31]:
a2[0,1]

2

In [32]:
a2[1,3]

8

In [ ]:
#math operations 

In [33]:
a=np.array([1,2,3,4,5])
a-5

array([-4, -3, -2, -1,  0])

In [34]:
a*5

array([ 5, 10, 15, 20, 25])

In [35]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [36]:
a%5

array([1, 2, 3, 4, 0], dtype=int32)

In [38]:
a=np.arange(5,15,2)
a

array([ 5,  7,  9, 11, 13])

In [39]:
np.mean(a)

9.0

In [40]:
np.median(a)

9.0

In [41]:
np.std(a)

2.8284271247461903

In [ ]:
#slicing


In [43]:
a5[0:3]

array([0, 1, 2])

In [44]:
a5[:4]

array([0, 1, 2, 3])

In [45]:
a5[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [46]:
a5[1:6:2]

array([1, 3, 5])

In [47]:
a5[::2]

array([0, 2, 4, 6, 8])

In [48]:
a5[-1]

9

In [49]:
a2[1,0:2]

array([5, 6])

In [50]:
a5[-4:-1]

array([6, 7, 8])

In [51]:
a2[:-1]

array([[1, 2, 3, 4]])

In [52]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
a[::-1,::-1]

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [54]:
np.flip(a,axis=0)

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [55]:
np.flip(a,axis=1)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6]])

In [ ]:
#special array


In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

In [60]:
np.random.rand(2,3)

array([[0.29537262, 0.44158093, 0.33716575],
       [0.48987386, 0.34182124, 0.67973057]])

In [61]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(3,dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [64]:
np.eye(3,dtype=np.int32,k=1)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [65]:
np.eye(3,dtype=np.int32,k=-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [ ]:
#stacking and concatenating

In [67]:
a=np.arange(0,5)
b=np.arange(6,11 )
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [68]:
np.hstack((a,b))

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10])

In [69]:
np.concatenate((a,b),axis=0)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10])

In [70]:
np.concatenate((a,b),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [73]:
a=np.array([[1,2],[3,4]])
np.append(a,[[5,6]],axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
a=np.array([[1,2],[3,4]])
np.append(a,[[5],[6]],axis=1)

array([[1, 2, 5],
       [3, 4, 6]])